### ISSUE TITLE
WebUI Redesign Issue Tracker

### ISSUE THREAD

**Issue by harshithmohan** [ShokoAnime/Shoko-WebUI#417]
- Bugs
  - [x] Relation exclusions checkboxes don't auto-check on the initial render
  - [x] WebUI settings not getting saved properly
  - [x] Pressing enter on "Remember Me" checkbox doesn't log in
  - [x] Unrecognized files: Checkboxes stay when data is refetched

- To-Do/Missing Things
  - [x] Add plex settings
  - [x] Finish user management settings
  - [x] AniDB ban indicator
  - [x] Auto refresh stats using events
  - [x] Convert everything to RTK Query
  - [x] Show messages on dashboard panels when empty
  - [ ] Add prompt if closing tab in layout edit mode

**Comment by ElementalCrisis** [comment]
**UI/UX Issues**

- [ ] None of the widgets update live, data is only updated on refresh and is static. The only exception is the queue which once refreshed, will show tasks being completed. 
- [ ] Actions/Utilites nav item should be highlighted when sidepanel is open.
- [ ] Sidepanel is missing the border on the right-side of it. 
- [ ] Disable all links to sections we are not testing to avoid user confusion. 
- [ ] In Actions, user should be able to click the header itself to expand the section and not just the arrow. 
- [ ] Already known but adding for reference, transitions for sidepanel.
- [ ] Button highlight/underline for visual effect.

**Bugs**

- [ ] Unrecognized list does not update on change, file will stay in there until you open a tab. 

To-Do/Missing Things

- [ ] Toast notifications for every action/user click button.

**Comment by ElementalCrisis** [comment]
Redesigned Import Folder listing.
![image](https://user-images.githubusercontent.com/9443295/199395645-01381c43-fd2c-4ab4-a73c-017e83a9a2b3.png)

**Comment by harshithmohan** [comment]
@ElementalCrisis Removed Image path from the checklist, that's a shoko desktop setting

**Comment by revam** [comment]
> Removed Image path from the checklist, that's a shoko desktop setting

It is not though.

**Comment by ElementalCrisis** [comment]
I'm inclined to leave it off as we don't do any file moving if the user changes it.

**Comment by harshithmohan** [comment]
> > Removed Image path from the checklist, that's a shoko desktop setting
> 
> It is not though.

Refer to the actual issue, they specifically mentioned desktop images path.
